version: "3.7"

services:
  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - papabroccoli_network
    volumes:
      - /home/als900915/nginx.conf:/etc/nginx/nginx.conf
      - papabroccoli_static:/data/static/
      - papabroccoli_media:/data/media/

  django:
    image: papabroccoli:4
    networks:
      - papabroccoli_network
    volumes:
      - papabroccoli_static:/home/practice/staticfiles/
      - papabroccoli_media:/home/practice/media/

  mariadb:
    image: mariadb:10.5
    networks:
      - papabroccoli_network
    volumes:
      - papabroccoli_mariadb:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: 1234
      MARIADB_DATABASE: django
      MARIADB_USER: django
      MARIADB_PASSWORD: 1234


networks:
  papabroccoli_network:


volumes:
  papabroccoli_static:
  papabroccoli_media:
  papabroccoli_mariadb:
